name: glscopeclient

on:
  workflow_dispatch:
  push:
    paths: '.github/workflows/glscopeclient.yml'
    branches:
      - main
  schedule:
    - cron: "13 0 * * *"
jobs:
  build-glscopeclient:
    name: Build glscopeclient
    runs-on: windows-2019

    steps:
      - name: Setup Msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-glm
            mingw-w64-x86_64-libsigc++
            mingw-w64-x86_64-gtkmm3
            mingw-w64-x86_64-yaml-cpp
            mingw-w64-x86_64-glew
            mingw-w64-x86_64-opencl-headers

      - name: Checkout ffts
        uses: actions/checkout@v2
        with:
          repository: anthonix/ffts
          path: ffts

      - name: Build ffts
        shell: msys2 {0}
        working-directory: ffts
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=$MSYSTEM_PREFIX -DENABLE_SHARED=ON ..
          mingw32-make -j4
          mingw32-make install

      - name: Checkout scopehal-apps
        uses: actions/checkout@v2
        with:
          repository: azonenberg/scopehal-apps
          path: scopehal-apps
          submodules: recursive
          
      - name: Build scopehal-apps
        shell: msys2 {0}
        working-directory: scopehal-apps
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DLIBFFTS_INCLUDE_DIR=$MSYSTEM_PREFIX/include/ffts -DLIBFFTS_LIBRARIES=$MSYSTEM_PREFIX/lib/libffts_static.a -DBUILD_TESTING=OFF ..
          mingw32-make -j4

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.2.1
        with:
          path: ./*
          name: glscopeclient
   
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.2.1
        with:
          path: $MSYSTEM_PREFIX/lib/*
          name: msys_libs
